version: '3.7'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: admin 
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: StudentApi
    volumes: 
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  student-management:
    build: .
    ports: 
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./:/app #sync app directory in container with local
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=admin
      - DB_NAME=StudentApi
      - DB_PASSWORD=admin
volumes:
  pgdata: