version: '3.7'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: admin 
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: StudentApi
    restart: always
    volumes: 
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  student-management:
    build: .
    ports: 
      - "3000:3000"
    restart: always
    depends_on:
      - db
    volumes:
      - ./:/app #sync app directory in container with local
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=admin
      - DB_NAME=StudentApi
      - DB_PASSWORD=admin
  graphql-engine:
    image: hasura/graphql-engine:latest
    ports:
    - "8080:8080"
    depends_on:
    - db
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://admin:admin@db:5432/StudentApi
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_DEV_MODE: "true" 
      HASURA_GRAPHQL_ENABLE_LOG_TYPES: startup, http-log, webhook-log
      REMOTE_SCHEMA_ENDPOINT: http://student-management:3000/graphql
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
  pgdata: